definitions:
  model.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: API文档
  version: 1.0.0
paths:
  /login:
    post:
      description: 用户登陆
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: 用户登陆
      tags:
      - 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
